import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import type { LocalActor } from "../auth/actor";
import { PublicApi, PublicApiRequestError } from "./public-api";
import type { AnswerSubmissionResult, Leaderboard, PublicContent, PublicContentPage, PublicContentSummary, PublishedQuiz, QuizAttempt, XpSummary } from "./types";
import { clearLocalViewerActor, initialViewerActor, isLocalActorId, saveLocalViewerActor } from "./viewer-session";
import tabiiLogoUrl from "../../../gorseller/tabii-logo-png_seeklogo-481975.png";
import platformArtworkUrl from "../../../gorseller/tabii-dijital-platform-2041030.jpg";

const PAGE_SIZE = 12;
type View = "home" | "profile" | "leaderboard";
interface ViewerRoute { contentId: string | null; quizId: string | null; view: View; }

export function UserApp() {
  const [actor, setActor] = useState<LocalActor | null>(initialViewerActor);
  const api = useMemo(() => actor ? new PublicApi(actor) : null, [actor]);
  const [route, setRoute] = useState<ViewerRoute>(readRoute);

  useEffect(() => {
    const updateRoute = () => setRoute(readRoute());
    window.addEventListener("popstate", updateRoute);
    return () => window.removeEventListener("popstate", updateRoute);
  }, []);

  function navigate(nextRoute: Partial<ViewerRoute>) {
    const next = { ...route, ...nextRoute };
    const url = new URL(window.location.href);
    setRouteParam(url, "content", next.contentId); setRouteParam(url, "quiz", next.quizId);
    setRouteParam(url, "view", next.view === "home" ? null : next.view);
    window.history.pushState({}, "", url); setRoute(next); window.scrollTo({ top: 0, behavior: "smooth" });
  }

  if (!actor || !api) return <LocalSignIn onSignedIn={setActor} />;
  return <main className="viewer-shell">
    <SiteHeader actor={actor} view={route.view} onNavigate={(view) => navigate({ view, contentId: null, quizId: null })} onSignOut={() => { clearLocalViewerActor(); setActor(null); }} />
    {route.quizId ? <QuizExperience api={api} quizId={route.quizId} onExit={() => navigate({ quizId: null })} onViewProfile={() => navigate({ quizId: null, contentId: null, view: "profile" })} /> : route.contentId
      ? <ContentDetail api={api} contentId={route.contentId} onBack={() => navigate({ contentId: null })} onStartQuiz={(quizId) => navigate({ quizId })} />
      : route.view === "profile" ? <Profile api={api} /> : route.view === "leaderboard" ? <LeaderboardView api={api} /> : <Catalogue api={api} onOpen={(contentId) => navigate({ contentId })} />}
  </main>;
}

function SiteHeader({ actor, view, onNavigate, onSignOut }: { actor: LocalActor; view: View; onNavigate: (view: View) => void; onSignOut: () => void }) {
  return <header className="viewer-header"><a className="viewer-brand" href="/user.html" onClick={(event) => { event.preventDefault(); onNavigate("home"); }} aria-label="Hikâye İzi ana sayfası"><img src={tabiiLogoUrl} alt="tabii" /><span><strong>Hikâye</strong> İzi</span><em>izle · hatırla · oyna</em></a>
    <nav aria-label="Kullanıcı menüsü"><button className={view === "home" ? "active" : ""} onClick={() => onNavigate("home")}>Keşfet</button><button className={view === "leaderboard" ? "active" : ""} onClick={() => onNavigate("leaderboard")}>Sıralama</button><button className={view === "profile" ? "active" : ""} onClick={() => onNavigate("profile")}>Profil</button></nav><p><span>Yerel deneme</span><code>{actor.id}</code><button className="sign-out" onClick={onSignOut}>Çıkış</button></p></header>;
}

function LocalSignIn({ onSignedIn }: { onSignedIn: (actor: LocalActor) => void }) {
  const [actorId, setActorId] = useState(""); const [error, setError] = useState("");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!isLocalActorId(actorId)) { setError("Yerel deneme için geçerli bir UUID girin."); return; } setError(""); onSignedIn(saveLocalViewerActor(actorId.trim())); }
  return <main className="viewer-shell sign-in-shell"><section className="local-access"><p className="kicker">Yerel deneme oturumu</p><h1>Keşfetmeye hazır mısın?</h1><p>Bu ekran gerçek bir tabii girişi değildir. Yalnız geliştirme ortamındaki geçici USER kimliğini backend'e gönderir.</p><form onSubmit={submit}><label htmlFor="local-actor-id">Kullanıcı kimliği (UUID)</label><input id="local-actor-id" value={actorId} onChange={(event) => { setActorId(event.target.value); if (error) setError(""); }} placeholder="11111111-1111-1111-1111-111111111111" autoComplete="off" required /><button>Yerel oturumu başlat</button></form>{error && <p className="form-error" role="alert">{error}</p>}<p className="sign-in-note">Kurum OIDC giriş sözleşmesi henüz belirlenmediği için production login bu uygulamada yoktur.</p></section></main>;
}

function Catalogue({ api, onOpen }: { api: PublicApi; onOpen: (contentId: string) => void }) {
  const [page, setPage] = useState<PublicContentPage | null>(null); const [error, setError] = useState<PublicApiRequestError | null>(null); const [isLoading, setIsLoading] = useState(true); const [currentPage, setCurrentPage] = useState(0);
  useEffect(() => { let active = true; setIsLoading(true); setError(null); api.listContents(currentPage, PAGE_SIZE).then((result) => { if (active) setPage(result); }).catch((reason: unknown) => { if (active) setError(asPublicError(reason)); }).finally(() => { if (active) setIsLoading(false); }); return () => { active = false; }; }, [api, currentPage]);
  return <><section className="viewer-hero"><img className="hero-artwork" src={platformArtworkUrl} alt="" /><div className="hero-copy"><p>Hikâye İzi</p><h1>İzlediğin hikâyenin izini sür.</h1><p className="hero-description">Bir sahneyi hatırla, kısa bir meydan okumayı tamamla ve kendi XP yolunu oluştur.</p></div></section><section className="catalogue-section" aria-labelledby="catalogue-heading"><div className="section-heading"><div><p className="kicker">Meydan okuma seç</p><h2 id="catalogue-heading">Hikâyeni seç, izini bırak.</h2></div>{page && <p>{page.totalItems} yayın</p>}</div><ErrorNotice error={error} />{isLoading ? <p className="loading-copy" aria-live="polite">İçerikler yükleniyor…</p> : page && <><ul className="viewer-grid">{page.items.map((content) => <ContentTile key={content.id} api={api} content={content} onOpen={() => onOpen(content.id)} />)}</ul>{page.items.length === 0 && <p className="empty-state">Henüz yayınlanmış içerik yok.</p>}<Pagination page={page} onPageChange={setCurrentPage} /></>}</section></>;
}

function ContentTile({ api, content, onOpen }: { api: PublicApi; content: PublicContentSummary; onOpen: () => void }) { return <li><article className="viewer-tile"><button className="tile-button" onClick={onOpen} aria-label={`${content.title} ayrıntılarını aç`}><Cover api={api} content={content} /><span className="tile-copy"><span className="content-label">{content.contentType === "SERIES" ? "Dizi" : "Film"}</span><strong>{content.title}</strong><span>{content.description || "Bu içerik için kısa açıklama yakında."}</span></span></button></article></li>; }

function ContentDetail({ api, contentId, onBack, onStartQuiz }: { api: PublicApi; contentId: string; onBack: () => void; onStartQuiz: (quizId: string) => void }) {
  const [content, setContent] = useState<PublicContent | null>(null); const [quizzes, setQuizzes] = useState<PublishedQuiz[]>([]); const [error, setError] = useState<PublicApiRequestError | null>(null); const [isLoading, setIsLoading] = useState(true);
  useEffect(() => { let active = true; setIsLoading(true); setError(null); Promise.allSettled([api.getContent(contentId), api.listQuizzes(contentId)]).then(([contentResult, quizResult]) => { if (!active) return; if (contentResult.status === "fulfilled") setContent(contentResult.value); else setError(asPublicError(contentResult.reason)); if (quizResult.status === "fulfilled") setQuizzes(quizResult.value); else if (contentResult.status === "fulfilled") setError(asPublicError(quizResult.reason)); }).finally(() => { if (active) setIsLoading(false); }); return () => { active = false; }; }, [api, contentId]);
  if (isLoading) return <p className="loading-copy" aria-live="polite">İçerik hazırlanıyor…</p>; if (!content) return <section className="detail-section"><ErrorNotice error={error} /><button className="text-button" onClick={onBack}>← Keşfete dön</button></section>;
  return <><section className="detail-hero-viewer"><Cover api={api} content={content} prominent /><div><button className="text-button light" onClick={onBack}>← Keşfete dön</button><p className="kicker">{content.contentType === "SERIES" ? "Dizi" : "Film"}</p><h1>{content.title}</h1><p>{content.description || "Bu içerik için kısa açıklama yakında."}</p></div></section><section className="detail-section"><ErrorNotice error={error} /><QuizShelf quizzes={quizzes} onStartQuiz={onStartQuiz} />{content.contentType === "SERIES" && <EpisodeShelf content={content} />}</section></>;
}

function QuizShelf({ quizzes, onStartQuiz }: { quizzes: PublishedQuiz[]; onStartQuiz: (quizId: string) => void }) { return <section className="quiz-shelf" aria-labelledby="quiz-heading"><div className="section-heading"><div><p className="kicker">Etkileşim</p><h2 id="quiz-heading">Bu içerikle ilgili quizler</h2></div><p>{quizzes.length} quiz</p></div>{quizzes.length === 0 ? <p className="empty-state">Bu içerik için henüz yayınlanmış bir quiz yok.</p> : <ul className="quiz-list">{quizzes.map((quiz) => <li key={quiz.quizId}><article><p className="content-label">{quiz.questions.length} soru</p><h3>{quiz.title}</h3><p>{quiz.description || "Hazır olduğunda hikâyeyi ne kadar hatırladığını dene."}</p><button className="quiz-start" onClick={() => onStartQuiz(quiz.quizId)}>Quiz'e başla <span aria-hidden="true">→</span></button></article></li>)}</ul>}</section>; }

function QuizExperience({ api, quizId, onExit, onViewProfile }: { api: PublicApi; quizId: string; onExit: () => void; onViewProfile: () => void }) {
  const [quiz, setQuiz] = useState<PublishedQuiz | null>(null); const [attempt, setAttempt] = useState<QuizAttempt | null>(null); const [answerResult, setAnswerResult] = useState<AnswerSubmissionResult | null>(null); const [error, setError] = useState<PublicApiRequestError | null>(null); const [isLoading, setIsLoading] = useState(true); const [isStarting, setIsStarting] = useState(false); const [isSubmitting, setIsSubmitting] = useState(false); const [pendingAnswer, setPendingAnswer] = useState<{ questionId: string; optionId: string; key: string } | null>(null);
  useEffect(() => { let active = true; api.getQuiz(quizId).then((loadedQuiz) => { if (active) setQuiz(loadedQuiz); }).catch((reason: unknown) => { if (active) setError(asPublicError(reason)); }).finally(() => { if (active) setIsLoading(false); }); return () => { active = false; }; }, [api, quizId]);
  async function start(timingPolicyVersion: QuizAttempt["timingPolicyVersion"]) { setIsStarting(true); setError(null); try { setAttempt(await api.startAttempt(quizId, timingPolicyVersion)); } catch (reason) { setError(asPublicError(reason)); } finally { setIsStarting(false); } }
  async function submit(questionId: string, optionId: string, key = createRequestKey()) { setIsSubmitting(true); setError(null); const pending = { questionId, optionId, key }; setPendingAnswer(pending); try { setAnswerResult(await api.submitAnswer(attempt!.attemptId, questionId, optionId, key)); } catch (reason) { setError(asPublicError(reason)); } finally { setIsSubmitting(false); } }
  function continueAfterAnswer() { if (!attempt || !answerResult) return; const nextAttempt = { ...attempt, status: answerResult.attemptStatus, score: answerResult.score, earnedXp: answerResult.earnedXp, answeredQuestionCount: attempt.answeredQuestionCount + 1, currentQuestion: answerResult.nextQuestion, submittedAnswers: [...attempt.submittedAnswers, answerResult.feedback] }; setAttempt(nextAttempt); setAnswerResult(null); setPendingAnswer(null); }
  if (isLoading) return <p className="loading-copy" aria-live="polite">Quiz hazırlanıyor…</p>; if (!quiz) return <section className="detail-section"><ErrorNotice error={error} /><button className="text-button" onClick={onExit}>← Geri dön</button></section>;
  if (!attempt) return <section className="quiz-intro"><p className="kicker">{quiz.questions.length} soru · Süre seçimi</p><h1>{quiz.title}</h1><p>{quiz.description || "Bu hikâyeyi ne kadar hatırladığını gör."}</p><ErrorNotice error={error} /><div className="timing-choice"><button disabled={isStarting} onClick={() => start("STANDARD_V1")}><strong>Standart süre</strong><span>5 dakika</span></button><button disabled={isStarting} onClick={() => start("EXTENDED_V1")}><strong>Uzatılmış süre</strong><span>50 dakika · puanı değiştirmez</span></button></div><button className="text-button" onClick={onExit}>Vazgeç</button></section>;
  if (attempt.status === "COMPLETED" && !answerResult) return <QuizResult attempt={attempt} onExit={onExit} onViewProfile={onViewProfile} />;
  const question = attempt.currentQuestion; if (!question) return <QuizResult attempt={attempt} onExit={onExit} onViewProfile={onViewProfile} />;
  return <QuizQuestion api={api} attempt={attempt} question={question} answerResult={answerResult} error={error} isSubmitting={isSubmitting} pendingAnswer={pendingAnswer} onExit={onExit} onSubmit={submit} onContinue={continueAfterAnswer} />;
}

function QuizQuestion({ api, attempt, question, answerResult, error, isSubmitting, pendingAnswer, onExit, onSubmit, onContinue }: { api: PublicApi; attempt: QuizAttempt; question: NonNullable<QuizAttempt["currentQuestion"]>; answerResult: AnswerSubmissionResult | null; error: PublicApiRequestError | null; isSubmitting: boolean; pendingAnswer: { questionId: string; optionId: string; key: string } | null; onExit: () => void; onSubmit: (questionId: string, optionId: string, key?: string) => Promise<void>; onContinue: () => void }) {
  const remainingTime = useRemainingTime(attempt.status === "ACTIVE" ? attempt.deadline : null);
  const timeExpired = remainingTime === 0;
  return <section className="quiz-play"><header><button className="text-button" onClick={onExit}>← Quizden çık</button><div><span>Soru {attempt.answeredQuestionCount + 1} / {attempt.totalQuestionCount}</span><strong>{formatRemainingTime(remainingTime)}</strong></div><progress value={attempt.answeredQuestionCount} max={attempt.totalQuestionCount}>İlerleme</progress></header><ErrorNotice error={error} retry={pendingAnswer ? () => onSubmit(pendingAnswer.questionId, pendingAnswer.optionId, pendingAnswer.key) : undefined} />{timeExpired && !answerResult && <p className="time-expired" role="alert">Süre doldu. Bu attempt artık yeni cevap kabul etmez.</p>}{answerResult ? <AnswerReveal result={answerResult} onContinue={onContinue} /> : <><div className="question-card">{question.visual && <AuthenticatedImage api={api} src={question.visual.contentUrl} alt={question.visual.role === "INFORMATIVE" ? question.visual.alternativeText : ""} fallback={<p className="media-fallback">Soru görseli yüklenemedi. Erişilebilir soru metnini kullanabilirsiniz.</p>} />}<p className="kicker">{question.difficulty}</p><h1>{question.prompt}</h1>{question.accessiblePrompt && <p className="accessible-prompt">{question.accessiblePrompt}</p>}</div><div className="answer-options" role="group" aria-label="Cevap seçenekleri">{question.options.map((option) => <button key={option.optionId} disabled={isSubmitting || pendingAnswer !== null || timeExpired} onClick={() => onSubmit(question.questionId, option.optionId)}>{option.text}</button>)}</div></>}</section>;
}

function AnswerReveal({ result, onContinue }: { result: AnswerSubmissionResult; onContinue: () => void }) { return <section className={`answer-reveal ${result.feedback.correct ? "correct" : "incorrect"}`} aria-live="assertive"><p>{result.feedback.correct ? "Doğru cevap" : "Bu kez değil"}</p><h1>{result.feedback.awardedPoints} puan</h1><button onClick={onContinue}>{result.attemptStatus === "COMPLETED" ? "Sonucu gör" : "Sonraki soruya geç"} <span aria-hidden="true">→</span></button></section>; }
function QuizResult({ attempt, onExit, onViewProfile }: { attempt: QuizAttempt; onExit: () => void; onViewProfile: () => void }) { return <section className="quiz-result"><p className="kicker">Quiz tamamlandı</p><h1>{attempt.score} puan</h1><p>{attempt.earnedXp === null ? "XP işleniyor; profilinde kısa süre sonra görünebilir." : `+${attempt.earnedXp} XP kazandın.`}</p><div><button className="quiz-start" onClick={onViewProfile}>Profilime git</button><button className="text-button" onClick={onExit}>Keşfete dön</button></div></section>; }

function Profile({ api }: { api: PublicApi }) { const [data, setData] = useState<{ xp: XpSummary; leaderboard: Leaderboard } | null>(null); const [error, setError] = useState<PublicApiRequestError | null>(null); useEffect(() => { let active = true; Promise.all([api.getXp(), api.getGlobalLeaderboard()]).then(([xp, leaderboard]) => { if (active) setData({ xp, leaderboard }); }).catch((reason: unknown) => { if (active) setError(asPublicError(reason)); }); return () => { active = false; }; }, [api]); return <section className="detail-section profile-page"><p className="kicker">Profil</p><h1 className="story-title">İlerleme alanın</h1><ErrorNotice error={error} />{data ? <><div className="profile-stats"><article><span>Toplam XP</span><strong>{data.xp.totalXp}</strong></article><article><span>Tamamlanan işlem</span><strong>{data.xp.transactionCount}</strong></article><article><span>Global sıra</span><strong>{data.leaderboard.currentUser ? `#${data.leaderboard.currentUser.position}` : "—"}</strong></article></div><p className="profile-note">XP toplamı mesajlaşma consumer'ı çalışana kadar kısa süreli eski kalabilir.</p></> : <p className="loading-copy">Profilin hazırlanıyor…</p>}</section>; }
function LeaderboardView({ api }: { api: PublicApi }) { const [board, setBoard] = useState<Leaderboard | null>(null); const [error, setError] = useState<PublicApiRequestError | null>(null); useEffect(() => { let active = true; api.getGlobalLeaderboard().then((result) => { if (active) setBoard(result); }).catch((reason: unknown) => { if (active) setError(asPublicError(reason)); }); return () => { active = false; }; }, [api]); return <section className="detail-section leaderboard-page"><p className="kicker">Tüm zamanlar</p><h1 className="story-title">Sıralama</h1><ErrorNotice error={error} />{board ? <><p className="leaderboard-meta">{board.participantCount} katılımcı · {board.dataSource === "REDIS" ? "Güncellenen görünüm" : "Doğrulanmış kaynak"}</p><ol className="leaderboard-list">{board.leaders.map((entry) => <li className={entry.currentUser ? "current-user" : ""} key={entry.userId}><span>#{entry.position}</span><code>{shortId(entry.userId)}</code><strong>{entry.totalXp} XP</strong></li>)}</ol>{board.currentUser && !board.leaders.some((entry) => entry.currentUser) && <p className="own-rank">Senin sıran: #{board.currentUser.position} · {board.currentUser.totalXp} XP</p>}</> : <p className="loading-copy">Sıralama hazırlanıyor…</p>}</section>; }
function EpisodeShelf({ content }: { content: PublicContent }) { return <section className="episode-shelf" aria-labelledby="episodes-heading"><div className="section-heading"><div><p className="kicker">Bölümler</p><h2 id="episodes-heading">Nerede kalmıştın?</h2></div><p>{content.seasons.length} sezon</p></div><div className="season-list">{content.seasons.map((season) => <article key={season.id}><h3>Sezon {season.seasonNumber}<span>{season.title}</span></h3><ol>{season.episodes.map((episode) => <li key={episode.id}><span>{episode.episodeNumber}</span><div><strong>{episode.title}</strong>{episode.description && <p>{episode.description}</p>}</div></li>)}</ol></article>)}</div></section>; }
function Cover({ api, content, prominent = false }: { api: PublicApi; content: PublicContentSummary; prominent?: boolean }) { const className = `viewer-cover ${prominent ? "viewer-cover--prominent" : ""} viewer-cover--${content.contentType.toLowerCase()}`; return <div className={className}>{content.coverImageUrl ? <AuthenticatedImage api={api} src={content.coverImageUrl} alt={content.coverAlternativeText || ""} fallback={<span aria-hidden="true">{content.title.slice(0, 1)}</span>} /> : <span aria-hidden="true">{content.title.slice(0, 1)}</span>}</div>; }
function AuthenticatedImage({ api, src, alt, fallback }: { api: PublicApi; src: string; alt: string; fallback: ReactNode }) { const [objectUrl, setObjectUrl] = useState<string | null>(null); const [failed, setFailed] = useState(false); useEffect(() => { let active = true; let createdUrl: string | null = null; setObjectUrl(null); setFailed(false); api.getMedia(src).then((blob) => { if (!active) return; createdUrl = URL.createObjectURL(blob); setObjectUrl(createdUrl); }).catch(() => { if (active) setFailed(true); }); return () => { active = false; if (createdUrl) URL.revokeObjectURL(createdUrl); }; }, [api, src]); if (failed) return fallback; return objectUrl ? <img src={objectUrl} alt={alt} /> : <span className="media-loading" aria-hidden="true" />; }
function Pagination({ page, onPageChange }: { page: PublicContentPage; onPageChange: (page: number) => void }) { return <nav className="viewer-pagination" aria-label="İçerik sayfaları"><button disabled={page.page === 0} onClick={() => onPageChange(page.page - 1)}>Önceki</button><span>{page.page + 1} / {Math.max(page.totalPages, 1)}</span><button disabled={page.page + 1 >= page.totalPages} onClick={() => onPageChange(page.page + 1)}>Sonraki</button></nav>; }
function ErrorNotice({ error, retry }: { error: PublicApiRequestError | null; retry?: () => void }) { if (!error) return null; return <section className="viewer-error" role="alert"><h2>Şu an yüklenemedi</h2><p>{error.message}</p><p>Hata kodu: <code>{error.code}</code> · İz kimliği: <code>{error.traceId}</code></p>{retry && <button onClick={retry}>Tekrar dene</button>}</section>; }
function readRoute(): ViewerRoute { const query = new URLSearchParams(window.location.search); const view = query.get("view"); return { contentId: query.get("content"), quizId: query.get("quiz"), view: view === "profile" || view === "leaderboard" ? view : "home" }; }
function setRouteParam(url: URL, key: string, value: string | null) { if (value) url.searchParams.set(key, value); else url.searchParams.delete(key); }
function createRequestKey(): string { return globalThis.crypto?.randomUUID?.() ?? `answer-${Date.now()}-${Math.random().toString(36).slice(2)}`; }
function useRemainingTime(deadline: string | null) { const [now, setNow] = useState(Date.now); useEffect(() => { if (!deadline) return; setNow(Date.now()); const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, [deadline]); return deadline ? Math.max(0, Math.ceil((new Date(deadline).getTime() - now) / 1000)) : 0; }
function formatRemainingTime(seconds: number) { return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`; }
function shortId(value: string) { return `${value.slice(0, 8)}…`; }
function asPublicError(reason: unknown): PublicApiRequestError { return reason instanceof PublicApiRequestError ? reason : new PublicApiRequestError({ code: "UNEXPECTED_CLIENT_ERROR", message: "Beklenmeyen bir istemci hatası oluştu.", traceId: "unavailable", status: 0 }); }
